#!/usr/bin/env python3
"""Typeset the energy-budget results of energy_budget_nn.py into a PDF.

All numbers are computed by importing energy_budget_nn (single source of
truth); this file only formats. Output: analysis/energy_budget_nn_report.pdf
"""
import math
import subprocess
from pathlib import Path

import energy_budget_nn as eb

HERE = Path(__file__).resolve().parent
d = eb.sec_d()
c = eb.comb_nn()
s = eb.serial_nn(c)
rmac = c["rmac"]

r4096, r65k = d["rows"]

tex = r"""\documentclass[11pt]{article}
\usepackage[margin=2.4cm]{geometry}
\usepackage{booktabs,amsmath,amssymb,xcolor}
\usepackage[colorlinks=true,linkcolor=blue]{hyperref}
\newcommand{\dbm}{\,\mathrm{dBm}}
\begin{document}

\begin{center}
{\LARGE Client-side energy budget of the GTSRB CNN}\\[2mm]
{\large comb vs.\ time-serial encoding, in the Eq.~(5) convention of
Sec.~II\,D}\\[1mm]
2026-08-31 --- generated by \texttt{analysis/make\_energy\_report.py}
from \texttt{analysis/energy\_budget\_nn.py}
\end{center}

\section*{Convention (paper, Sec.~II\,D / Methods~G)}
$e_{\mathrm{ip}} = e_1+e_2+e_3$ with
$e_1 = P_x T_{\mathrm{air}}/(4N\,\eta_{\mathrm{radio}})$ (transmit; $P_x$
\emph{at the mixer}, $\eta_{\mathrm{radio}}=10\%%$),
$e_2 = 6\,e_{\mathrm{ADC}}/4N$, $e_3 = 8\,e_{\mathrm{dig}}/4N$
($e_{\mathrm{ADC}}=e_{\mathrm{dig}}=1$\,pJ; fixed 14\,pJ read-out fee per
answer). Component-level and input-referred on both sides: no DAC, no static
transceiver power, no SDR wall-plug; H100 reference 70\,fJ per real MAC
(arithmetic only). One complex inner product of length $N$ = $4N$ real MACs.

\section*{1.\ Reproduction of Sec.~II\,D (resolved inner products)}
\begin{center}\begin{tabular}{lrrrrrr}
\toprule
 & $P_{LO}$ & $P_{RF}$ at mixer & $e_1$ & fee ($e_2{+}e_3$) &
$e_{\mathrm{ip}}$ & paper\\
\midrule
$N=4096$  & $-3\dbm$ & %(px4)0.3f\,nW $=%(pd4)0.1f\dbm$$^{\dagger}$ &
%(e14)0.3f\,fJ & %(f4)0.3f\,fJ & \textbf{%(t4)0.2f\,fJ} & 1.47\,fJ\\
$N=65{,}536$ & $-3\dbm$ & %(px6)0.3f\,nW $=%(pd6)0.1f\dbm$ &
%(e16)0.3f\,fJ & %(f6)0.3f\,fJ & \textbf{%(t6)0.2f\,fJ} & 0.59\,fJ\\
\bottomrule
\end{tabular}\end{center}
Input powers: weight comb fixed at $P_{LO}=-3\dbm$ (paper, Methods~C);
data-comb $P_{RF}$ closed-loop tuned to the 25-dB guard-bin target and
frozen (paper) --- tabulated above.
GPU crossover $N\!\approx\!%(ncross)0.0f$ (paper: $N\gtrsim50$);
radio-floor bend $N\!\approx\!%(nbend)0.0f$ (paper: $6.5\times10^3$);
%(vs4)0.0f$\times$ / %(vs6)0.0f$\times$ below H100 (paper: 48$\times$/119$\times$).
\emph{All Sec.~D numbers reproduce.}
$^{\dagger}$backed out from the printed 1.47\,fJ ($P_x$ for $N{=}4096$ is not
stated in the draft). Open item: 117\,ns airtime per real MAC is $\sim$13\%%
above the bare frame arithmetic $(L{+}\mathrm{CP})/4N = 103$\,ns at
10\,MS/s --- presumably sync amortization; to be confirmed against the
original generator.

\section*{2.\ Comb CNN at $(P_{LO},P_{RF})=(-3,-65)\dbm$ at the mixer}
The data comb is inserted at the mixer RF port at $-65\dbm$ --- the
operating point of the frozen-battery demonstration as physically
delivered. Client pays the data comb only (weights = base-station side). Symbol counts from the fielded planner
(\texttt{plan\_layer}, as in \texttt{miwen\_overhead\_ratio.py});
r3plus: %(cmac)0.2f\,M complex MACs = %(rmacM)0.2f\,M real MACs,
%(ans)s answers, %(sym)s symbols ($+3.1\%%$ sync) $\to$
\textbf{%(tair)0.2f\,s airtime/image}.
\begin{center}\begin{tabular}{lrrrrr}
\toprule
layer & $D$ & sym/img & cMAC/img & answers & fee per real MAC\\
\midrule
%(layerrows)s
\bottomrule
\end{tabular}\end{center}
\begin{center}\begin{tabular}{lrr}
\toprule
 & per image & per real MAC\\
\midrule
$e_1$ (TX at $-65\dbm = 0.316$\,nW) & %(ce1)0.1f\,nJ & %(ce1m)0.2f\,fJ\\
read-out fee ($14$\,pJ $\times$ %(ans)s) & %(cfee)0.1f\,nJ & %(cfeem)0.2f\,fJ\\
\textbf{total} & \textbf{%(ctot)0.1f\,nJ} & \textbf{%(ctotm)0.2f\,fJ}
--- %(cvs)0.1f$\times$ below H100\\
\bottomrule
\end{tabular}\end{center}
The NN budget is \emph{read-out--fee dominated}, the opposite of Sec.~D's
large-$N$ points: the CNN's inner products are short
($D=75\ldots1600$), so the fixed 14\,pJ/answer amortizes poorly (conv1 pays
%(fee1)0.1f\,fJ per real MAC by itself). The comb packing is not the
problem --- airtime works out to %(airmac)0.0f\,ns per real MAC,
essentially Sec.~D's 117\,ns.

\section*{3.\ Serial CNN at $(P_{LO},P_{RF})=(-10,-24)\dbm$}
The measured low-drive serial arm
(\texttt{serial\_nn\_runner\_m10m24.py}, unpadded chain $\to$ commanded
$\approx$ device plane). One complex product per 3.2\,$\mu$s slot:
%(cmacs)s slots $\to$ \textbf{%(stair)0.1f\,s airtime/image}. Read-out fee
assumes the slow coherent integrate-and-dump read-out at the \emph{row}
rate (Sec.~D convention); the as-fielded per-sample SDR capture would
instead cost %(sfield)0.1f\,pJ per real MAC.
\begin{center}\begin{tabular}{lrr}
\toprule
 & per image & per real MAC\\
\midrule
$e_1$ (TX at $-24\dbm = 4.0\,\mu$W) & %(se1)0.1f\,$\mu$J & %(se1m)0.2f\,pJ\\
read-out fee & %(sfee)0.1f\,nJ & %(sfeem)0.2f\,fJ\\
\textbf{total} & \textbf{%(stot)0.1f\,$\mu$J} & \textbf{%(stotm)0.2f\,pJ}
--- %(svs)0.0f$\times$ \emph{above} H100\\
\bottomrule
\end{tabular}\end{center}

\section*{Bottom line}
\fcolorbox{black}{yellow!15}{\parbox{0.94\textwidth}{
\textbf{Sec.~D reproduces exactly} (1.47 / 0.59\,fJ per real MAC, crossover
$N\!\approx\!50$, bend $N\!\approx\!6.5{\times}10^3$).
\textbf{Comb CNN at $(-3,-65)\dbm$: %(ctot)0.0f\,nJ/image =
%(ctotm)0.1f\,fJ per real MAC, %(cvs)0.1f$\times$ below the H100 line} ---
but unlike the large-$N$ inner products the budget is 98\%% read-out fee,
because the network's inner products are short; the radio itself is nearly
free (%(ce1m)0.2f\,fJ). \textbf{Serial CNN at $(-10,-24)\dbm$:
%(stot)0.0f\,$\mu$J/image = %(stotm)0.1f\,pJ per real MAC,
%(svs)0.0f$\times$ above H100} --- serial's \emph{radio} term is
$\sim$10$^5\times$ the comb's ($+41$\,dB power, $-24$ vs.\ $-65\dbm$,
$\times$ 8$\times$ airtime per MAC, 0.8\,$\mu$s vs.\ %(airmac)0.0f\,ns);
the \emph{totals} differ 2{,}000$\times$ because both pay the same read-out
fee, which dominates the comb budget. At the headline
$(0,0)\dbm$ serial point $e_1$ grows another $+24$\,dB ($\approx$8\,nJ per
real MAC). Frequency multiplexing, not the mixer, is what makes the NN
energy story work.}}

\vspace{2mm}
\noindent\small Assumptions (knobs in the code): sync overhead $1/32$;
one average per symbol; capture/re-tune gaps excluded; client pays the
data-comb port only; Sec.~D exclusions throughout. Numbers tagged
[paper]/[repo]/[derived] in \texttt{energy\_budget\_nn.py}.
\end{document}
"""

layerrows = "\n".join(
    rf"{l['name']} & {l['D']} & {l['sym']:,} & {l['cmac']:,} & "
    rf"{l['answers']:,} & {l['fee_rmac']*1e15:.1f}\,fJ\\"
    for l in c["layers"])

tex = tex % dict(
    px4=r4096["px"] * 1e9, e14=r4096["e1"] * 1e15, f4=r4096["fee"] * 1e15,
    t4=r4096["eip"] * 1e15, pd4=10 * math.log10(r4096["px"] / 1e-3),
    px6=r65k["px"] * 1e9, e16=r65k["e1"] * 1e15, f6=r65k["fee"] * 1e15,
    t6=r65k["eip"] * 1e15, pd6=10 * math.log10(r65k["px"] / 1e-3),
    ncross=d["n_cross"], nbend=d["n_bend"],
    vs4=d["vs_h100"][0], vs6=d["vs_h100"][1],
    cmac=c["cmac"] / 1e6, rmacM=rmac / 1e6, ans=f"{c['answers']:,}",
    sym=f"{c['tot_sym']:,}", tair=c["t_air"], layerrows=layerrows,
    ce1=c["e1_img"] * 1e9, ce1m=c["e1_img"] / rmac * 1e15,
    cfee=c["fee_img"] * 1e9, cfeem=c["fee_img"] / rmac * 1e15,
    ctot=c["tot_img"] * 1e9, ctotm=c["tot_rmac"] * 1e15, cvs=c["vs_h100"],
    fee1=c["layers"][0]["fee_rmac"] * 1e15,
    airmac=c["t_air"] / rmac * 1e9,
    cmacs=f"{c['cmac']:,}", stair=s["t_air"],
    sfield=s["e2_fielded_rmac"] * 1e12,
    se1=s["e1_img"] * 1e6, se1m=s["e1_img"] / rmac * 1e12,
    sfee=s["fee_img"] * 1e9, sfeem=s["fee_img"] / rmac * 1e15,
    stot=s["tot_img"] * 1e6, stotm=s["tot_rmac"] * 1e12, svs=s["vs_h100"])

out = HERE / "energy_budget_nn_report.tex"
out.write_text(tex)
for _ in range(2):
    subprocess.run(["pdflatex", "-interaction=nonstopmode",
                    "-output-directory", str(HERE), out.name],
                   cwd=HERE, capture_output=True, check=True)
print(f"wrote {HERE / 'energy_budget_nn_report.pdf'}")
